version: '1'

services:
  client:
    build: ./client
    container_name: client
    ports:
      - "3000:3000"
  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"    

